server:
  port: 50805
spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3316/goldbuy?useSSL=false&allowMultiQueries=true
    username: root
    password: mysql@1qaz!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      connection-timeout: 60000
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-wait: 10000ms
    timeout: 10000ms

logging:
  path: ../logs
  file: manage.log